<?php

namespace LeavesOvertimeBundle\Repository;

/**
 * BalanceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalanceLogRepository extends \Doctrine\ORM\EntityRepository
{
}
