<?php

namespace LeavesOvertimeBundle\Repository;

/**
 * BusinessUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessUnitRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * @param $businessUnitId
     *
     * @return mixed
     */
    public function findReferencedEmployees($businessUnitId) {
        $query = $this->getEntityManager()->createQuery(
        'SELECT e.id, e.lastName, e.firstName
                FROM LeavesOvertimeBundle:Employee e
                JOIN e.businessUnit bu
                WHERE bu.id = :buID
                ORDER BY e.lastName, e.firstName ASC'
        )->setParameter('buID', $businessUnitId);
    
        return $query->getResult();
    }
}
