<?php

namespace LeavesOvertimeBundle\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getQueryBuilderEmployeesByLastName() {
        return $this->createQueryBuilder('jt')->orderBy('jt.lastName', 'ASC');
    }
    
    public function getEmployeesOrderLastName() {
        return $this->findAll();
    }
}
