<?php

namespace LeavesOvertimeBundle\Repository;

/**
 * EntityBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
