<?php

namespace LeavesOvertimeBundle\Repository;

/**
 * JobTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
