<?php

namespace LeavesOvertimeBundle\Repository;

/**
 * PublicHolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicHolidayRepository extends \Doctrine\ORM\EntityRepository
{
}
