imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@LeavesOvertimeBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    datetime_format_export: 'd M Y H:i:s'
    date_format_export: 'd M Y'
    from_email: 'noreply@leaves-system.com'
    base_dn: 'dc=example,dc=com'
    dn_username_attribute: 'uid'
    leaves_email_signature_name: 'ACSHRM'

# LDAP config here
fr3d_ldap:
    driver:
        host: ldap.forumsys.com
    user:
        baseDn: '%base_dn%'
        attributes:
            - { ldap_attr: '%dn_username_attribute%',  user_method: setUsername }
            - { ldap_attr: mail,  user_method: setEmail }
            - { ldap_attr: cn,  user_method: setFirstname }
            - { ldap_attr: sn,  user_method: setLastname }
        filter: (&(ObjectClass=person))

#    driver:
#        host: ros.mu
##        accountDomainName: ros
#        accountDomainNameShort: ros
##        accountFilterFormat: (&('sAMAccountName'=%s))
#        username: leaves
#        password: P@55w0rd
#    user:
#        baseDn: '%base_dn%'
#        attributes:
#            - { ldap_attr: samaccountname,  user_method: setUsername }
##            - { ldap_attr: mail,  user_method: setEmail }
##            - { ldap_attr: cn,  user_method: setFirstname }
##            - { ldap_attr: sn,  user_method: setLastname }
##        filter: (&(ObjectClass=person))
#        usernameAttribute: 'sAMAccountName'
#    service:
#        user_hydrator: leaves_overtime.ldap.user_hydrator

sonata_admin:
    title: Leaves & Overtime
#    title_logo: web/bundles/leavesovertime/axa-logo.svg
    templates:
        # Override default template
        layout: LeavesOvertimeBundle:SonataAdmin:standard_layout.html.twig
    show_mosaic_button:   false
    security:
        handler: sonata.admin.security.handler.role

#        role_admin: ROLE_ADMIN
#        role_super_admin: ROLE_SUPER_ADMIN

#        information:
#            EMPLOYEE:    [VIEW, LIST, EXPORT]
#            SUPERVISOR:    [OPERATOR]
#            ADMIN:    [MASTER]

# Sonata User Bundle
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          LeavesOvertimeBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User #Sonata\UserBundle\Entity\BaseUser

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group #Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    from_email:
        address:        '%from_email%'
        sender_name:    AXA Leaves & Overtime System

# Sonata Admin Bundle
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

framework:
    templating:
        engines: ['twig']
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
        # Sonata User Bundle
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:
        type: '%mailer_spool_type%'
        path: '%mailer_spool_path%'