parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: axa_hrm
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: mail.axa-customerservices.com
    mailer_user: svc_hrm
    mailer_password: 'Password.$1'
#    mailer_spool_type: file
#    mailer_spool_path: 'E:\Mails'
    mailer_from_email: 'noreply@leaves-management-system.com'