parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: axa_hrm
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    mailer_spool_type: null
    mailer_spool_path: null
    mailer_from_email: 'test-environment@leaves-management-system.com'