services:
    leaves_overtime.data_fixtures.email_template_fixture:
        class: LeavesOvertimeBundle\DataFixtures\GeneralDataFixture
        tags: [doctrine.fixture.orm]

    leaves_overtime.common.utility:
        class: LeavesOvertimeBundle\Common\Utility
        arguments: ["@service_container"]

    doctrine.listener.audit_subsriber:
        class:     LeavesOvertimeBundle\EventListener\AuditSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, lazy: true }

    doctrine.listener.leaves_subscriber:
      class: LeavesOvertimeBundle\EventListener\LeavesSubscriber
      arguments: ["@security.token_storage", "@service_container"]
      tags:
        - { name: doctrine.event_subscriber }

    doctrine.listener.user_import_listener:
      class: LeavesOvertimeBundle\EventListener\UserImportListener
      arguments: ["@service_container"]
      tags:
        - { name: doctrine.event_listener, event: prePersist, lazy: true }

    leaves_overtime.admin.business_unit:
        class: LeavesOvertimeBundle\Admin\BusinessUnitAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\BusinessUnit, LeavesOvertimeBundle:BusinessUnitAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Business Unit }
        public: true

    leaves_overtime.admin.department:
        class: LeavesOvertimeBundle\Admin\DepartmentAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\Department, LeavesOvertimeBundle:DepartmentAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Department }
        public: true

    leaves_overtime.admin.job_title:
        class: LeavesOvertimeBundle\Admin\JobTitleAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\JobTitle, LeavesOvertimeBundle:JobTitleAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Job Title }
        public: true

    leaves_overtime.admin.project:
        class: LeavesOvertimeBundle\Admin\ProjectAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\Project, LeavesOvertimeBundle:ProjectAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Project }
        public: true

    leaves_overtime.admin.email_template:
        class: LeavesOvertimeBundle\Admin\EmailTemplateAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\EmailTemplate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Email Template }
        public: true

    leaves_overtime.admin.public_holiday:
        class: LeavesOvertimeBundle\Admin\PublicHolidayAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\PublicHoliday, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Public Holiday }
        public: true

    leaves_overtime.admin.leaves:
        class: LeavesOvertimeBundle\Admin\LeavesAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\Leaves, LeavesOvertimeBundle:LeavesAdmin, '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: Leaves }
        public: true

    leaves_overtime.admin.user_import:
        class: LeavesOvertimeBundle\Admin\UserImportAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\UserImport, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: '%sonata.user.admin.groupname%', label: User Import, label_catalogue: "%sonata.user.admin.label_catalogue%", label_translator_strategy: "sonata.admin.label.strategy.native" }
        public: true

    leaves_overtime.admin.balance_log:
        class: LeavesOvertimeBundle\Admin\BalanceLogAdmin
        arguments: [~, LeavesOvertimeBundle\Entity\BalanceLog, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Organisation, label: BalanceLog }
        public: true
